enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[SoundCloud]
apkmirror-dlurl = "https://www.apkmirror.com/apk/soundcloud/soundcloud-soundcloud/"
uptodown-dlurl = "https://soundcloud.en.uptodown.com/android"
build-mode = "both"
cli-source = "ReVanced/revanced-cli"
patches-source = "ReVanced/revanced-patches"
cli-version = "dev"
patches-version = "dev"
included-patches = "'Predictive back gesture' 'Export internal data documents provider' 'Enable Android debugging' 'Remove screen capture restriction' 'Override certificate pinning' 'Remove screenshot restriction' 'Hide mock location' 'Export all activities'"
